=== laopeng2021/datayoga/packages/shared/jsonschema/block.descriptor.schema.json
{
  "$schema": "http://json-schema.org/draft-07/schema",
  "$id": "http://example.com/example.json",
  "type": "object",
  "title": "block type descriptor",
  "description": "Details of the type descriptor",
  "default": {},
  "examples": [
    {
      "title": "join",
      "type": "join",
      "description": "join two dataframes",
      "color": "cyan",
      "icon": "call_merge",
      "inputs": [
        {
          "id": "df1",
          "label": "df1",
          "type": "dataframe"
        },
        {
          "id": "df2",
          "label": "df2",
          "type": "dataframe"
        }
      ],
      "outputs": [
        {
          "id": "df",
          "label": "df",
          "type": "dataframe"
        }
      ],
      "comment_template": "join {{input 'df1'}}by {{input 'df2'}}"
    }
  ],
  "required": [
    "title",
    "type",
    "description",
    "color",
    "icon",
    "inputs",
    "outputs",
    "comment_template"
  ],
  "properties": {
    "title": {
      "$id": "#/properties/title",
      "type": "string",
      "title": "The title schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["join"]
    },
    "type": {
      "$id": "#/properties/type",
      "type": "string",
      "title": "The type schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["join"]
    },
    "description": {
      "$id": "#/properties/description",
      "type": "string",
      "title": "The description schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["join two dataframes"]
    },
    "color": {
      "$id": "#/properties/color",
      "type": "string",
      "title": "The color schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["cyan"]
    },
    "icon": {
      "$id": "#/properties/icon",
      "type": "string",
      "title": "The icon schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["call_merge"]
    },
    "inputs": {
      "$id": "#/properties/inputs",
      "type": "array",
      "title": "The inputs schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "examples": [
        [
          {
            "id": "df1",
            "label": "df1",
            "type": "dataframe"
          },
          {
            "id": "df2",
            "label": "df2",
            "type": "dataframe"
          }
        ]
      ],
      "additionalItems": true,
      "items": {
        "$id": "#/properties/inputs/items",
        "anyOf": [
          {
            "$id": "#/properties/inputs/items/anyOf/0",
            "type": "object",
            "title": "The first anyOf schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "examples": [
              {
                "id": "df1",
                "label": "df1",
                "type": "dataframe"
              }
            ],
            "required": ["id", "label", "type"],
            "properties": {
              "id": {
                "$id": "#/properties/inputs/items/anyOf/0/properties/id",
                "type": "string",
                "title": "The id schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": ["df1"]
              },
              "label": {
                "$id": "#/properties/inputs/items/anyOf/0/properties/label",
                "type": "string",
                "title": "The label schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": ["df1"]
              },
              "type": {
                "$id": "#/properties/inputs/items/anyOf/0/properties/type",
                "type": "string",
                "title": "The type schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": ["dataframe"]
              }
            },
            "additionalProperties": true
          }
        ]
      }
    },
    "outputs": {
      "$id": "#/properties/outputs",
      "type": "array",
      "title": "The outputs schema",
      "description": "An explanation about the purpose of this instance.",
      "default": [],
      "examples": [
        [
          {
            "id": "df",
            "label": "df",
            "type": "dataframe"
          }
        ]
      ],
      "additionalItems": true,
      "items": {
        "$id": "#/properties/outputs/items",
        "anyOf": [
          {
            "$id": "#/properties/outputs/items/anyOf/0",
            "type": "object",
            "title": "The first anyOf schema",
            "description": "An explanation about the purpose of this instance.",
            "default": {},
            "examples": [
              {
                "id": "df",
                "label": "df",
                "type": "dataframe"
              }
            ],
            "required": ["id", "label", "type"],
            "properties": {
              "id": {
                "$id": "#/properties/outputs/items/anyOf/0/properties/id",
                "type": "string",
                "title": "The id schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": ["df"]
              },
              "label": {
                "$id": "#/properties/outputs/items/anyOf/0/properties/label",
                "type": "string",
                "title": "The label schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": ["df"]
              },
              "type": {
                "$id": "#/properties/outputs/items/anyOf/0/properties/type",
                "type": "string",
                "title": "The type schema",
                "description": "An explanation about the purpose of this instance.",
                "default": "",
                "examples": ["dataframe"]
              }
            },
            "additionalProperties": true
          }
        ]
      }
    },
    "comment_template": {
      "$id": "#/properties/comment_template",
      "type": "string",
      "title": "The comment_template schema",
      "description": "An explanation about the purpose of this instance.",
      "default": "",
      "examples": ["join {{input 'df1'}}by {{input 'df2'}}"]
    }
  },
  "additionalProperties": true
}

=== laopeng2021/datayoga/blocks/concat_columnwise/descriptor.json
{
  "title": "columnwise merge",
  "type": "concat_columnwise",
  "description": "join two dataframes columnwise",
  "color": "red",
  "icon": "call_merge",
  "inputs": [
    { "id": "df1", "label": "df1", "type": "dataframe" },
    { "id": "df2", "label": "df2", "type": "dataframe" }
  ],
  "outputs": [{ "id": "df", "label": "df", "type": "dataframe" }],
  "comment_template": "column-wise merge"
}

=== laopeng2021/datayoga/blocks/sequence/descriptor.json
{
  "title": "Sequence",
  "type": "sequence",
  "description": "add auto-increment column to dataframe",
  "color": "peachpuff",
  "icon": "horizontal_split",
  "comment_template": "add auto-increment column {{props.column}}",
  "inputs": [
    {
      "id": "df",
      "label": "df",
      "type": "dataframe"
    }
  ],
  "outputs": [
    {
      "id": "df",
      "label": "df",
      "type": "dataframe"
    }
  ]
}

=== laopeng2021/datayoga/blocks/find_delta/descriptor.json
{
  "title": "find delta",
  "type": "find_delta",
  "description": "find delta between two dataframes",
  "color": "cyan",
  "icon": "call_merge",
  "inputs": [
    {
      "id": "existing",
      "label": "existing dataframe",
      "type": "dataframe"
    },
    {
      "id": "incoming",
      "label": "new dataframe",
      "type": "dataframe"
    }
  ],
  "outputs": [
    {
      "id": "insert",
      "label": "inserted rows",
      "type": "dataframe"
    },
    {
      "id": "update",
      "label": "updated rows",
      "type": "dataframe"
    },
    {
      "id": "delete",
      "label": "deleted rows",
      "type": "dataframe"
    }
  ],
  "comment_template": "find delta between {{input 'existing'}} and {{input 'incoming'}}"
}

=== laopeng2021/datayoga/blocks/filter/descriptor.json
{
  "title": "Filter",
  "type": "filter",
  "description": "filter rows",
  "color": "orange",
  "icon": "filter_list",
  "inputs": [{ "id": "df", "label": "df", "type": "dataframe" }],
  "outputs": [{ "id": "df", "label": "df", "type": "dataframe" }],
  "comment_template": "filter by {{props.condition}}"
}

=== laopeng2021/datayoga/blocks/sql/descriptor.json
{
  "title": "sql",
  "type": "sql",
  "description": "lookup a value in another dataframe and add as column",
  "color": "orange",
  "icon": "call_merge",
  "inputs": [{ "id": "df", "label": "df", "type": "dataframe" }],
  "outputs": [{ "id": "df", "label": "df", "type": "dataframe" }],
  "comment_template": "lookup {{props.column}}"
}

=== laopeng2021/datayoga/blocks/expression/descriptor.json
{
  "title": "Expression",
  "type": "expression",
  "description": "add expression column to dataframe",
  "color": "lightgreen",
  "icon": "horizontal_split",
  "comment_template": "add calculated columns {{#each props.columns}}{{this.column}} {{/each}}",
  "inputs": [
    {
      "id": "df",
      "label": "df",
      "type": "dataframe"
    }
  ],
  "outputs": [
    {
      "id": "df",
      "label": "df",
      "type": "dataframe"
    }
  ]
}

=== laopeng2021/datayoga/blocks/validate/descriptor.json
{
  "title": "Validation",
  "type": "validate",
  "description": "Validate data quality",
  "color": "lightgreen",
  "icon": "horizontal_split",
  "comment_template": "perform validations",
  "inputs": [{ "id": "df", "label": "df", "type": "dataframe" }],
  "outputs": [
    { "id": "success", "label": "success", "type": "notification" },
    { "id": "error", "label": "error", "type": "notification" }
  ]
}

=== laopeng2021/datayoga/blocks/load/descriptor.json
{
  "title": "load",
  "type": "load",
  "description": "load data into a datasource",
  "color": "#FFC300",
  "icon": "cloud_upload",
  "comment_template": "load {{input 'df'}} to {{props.table_name}}",
  "inputs": [
    {
      "id": "df",
      "label": "df",
      "type": "dataframe"
    }
  ],
  "outputs": []
}
